services:
    CoopTilleuls\ForgotPasswordBundle\Tests\TestBundle\EventSubscriber\ForgotPasswordEventSubscriber:
        class: CoopTilleuls\ForgotPasswordBundle\Tests\TestBundle\EventSubscriber\ForgotPasswordEventSubscriber
        arguments: ['@mailer', '@twig', '@doctrine']
        tags:
            - { name: kernel.event_subscriber }

    FeatureContext:
        class: FeatureContext
        public: true
        arguments: ['@test.client', '@doctrine', '@coop_tilleuls_forgot_password.manager.password_token']
