services:
    test.event_listener.forgot_password:
        class: CoopTilleuls\ForgotPasswordBundle\Tests\TestBundle\EventListener\ForgotPasswordEventListener
        arguments: ['@mailer', '@templating', '@doctrine']
        tags:
            - { name: kernel.event_listener, event: coop_tilleuls_forgot_password.create_token, method: onCreateToken }
            - { name: kernel.event_listener, event: coop_tilleuls_forgot_password.update_password, method: onUpdatePassword }
